services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        GITHUB_TOKEN: ${GIT_ACCES_TOKEN}
    env_file:
      - .env
      - .config
    ports:
      - "9123:80"
    volumes:
      - .:/var/www/html
      - ./docker-logs/nginx:/var/log/nginx
      - /var/log:/host/var/log
      - ~/.ssh:/var/www/.ssh