services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        GITHUB_TOKEN: ${GIT_ACCES_TOKEN}
    env_file:
      - .env
    ports:
      - "9123:80"
    volumes:
      - ./logs:/var/www/html/logs
      - ./data:/var/www/html/data
      - ./docker-logs/nginx:/var/log/nginx
      - ./src:/var/www/html/src
      - ./public:/var/www/html/public
      - ./temp:/var/www/html/temp
      - /var/log:/host/var/log:ro
      - ~/.ssh:/home/mariusz/.ssh:ro
    environment:
      APP_ENV: development
      LOG_DIR: /var/www/html/logs